# Workflow name
name: ESLint & TSC

# Event for the workflow
on: [pull_request]

# List of jobs
jobs:
 eslint-tsc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: ESLint
        run: bun run lint

      - name: TSC
        run: bun run type-check
